// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtET9ybafRaVDqqa0bjXQCFikYO8Wj20g',
    appId: '1:912787228925:web:395f5144dc2a81a65a9694',
    messagingSenderId: '912787228925',
    projectId: 'erasmusmoneymanager',
    authDomain: 'erasmusmoneymanager.firebaseapp.com',
    storageBucket: 'erasmusmoneymanager.appspot.com',
    measurementId: 'G-7JD0FXEN0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEn9nAK1BN5HEI44d2njtFRWDBD3feq98',
    appId: '1:912787228925:android:9c911bb36acca4ef5a9694',
    messagingSenderId: '912787228925',
    projectId: 'erasmusmoneymanager',
    storageBucket: 'erasmusmoneymanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-XroSXZYHr5cdjzzS6OP312kSFXTxXE',
    appId: '1:912787228925:ios:b22da86b901061505a9694',
    messagingSenderId: '912787228925',
    projectId: 'erasmusmoneymanager',
    storageBucket: 'erasmusmoneymanager.appspot.com',
    iosBundleId: 'com.example.erasmusMoneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5-XroSXZYHr5cdjzzS6OP312kSFXTxXE',
    appId: '1:912787228925:ios:b22da86b901061505a9694',
    messagingSenderId: '912787228925',
    projectId: 'erasmusmoneymanager',
    storageBucket: 'erasmusmoneymanager.appspot.com',
    iosBundleId: 'com.example.erasmusMoneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtET9ybafRaVDqqa0bjXQCFikYO8Wj20g',
    appId: '1:912787228925:web:9c21f39dd4ec62a05a9694',
    messagingSenderId: '912787228925',
    projectId: 'erasmusmoneymanager',
    authDomain: 'erasmusmoneymanager.firebaseapp.com',
    storageBucket: 'erasmusmoneymanager.appspot.com',
    measurementId: 'G-0RLW842GXS',
  );
}
